name: mfl-server

services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=mfl!lfm
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - mflnet
  mfl-server:
    image: mfl-server:latest
    restart: always
    volumes:
      - config:/mfl-server/config
    ports:
      - 80:80
    networks:
      - mflnet
networks:
  mflnet:
    driver: bridge
volumes:
  config:
    driver: local
  db:
    driver: local