name: "Build MFL terminal for linux"
inputs:
  arch:
    required: true
    type: string
runs:
  using: "composite"
  steps:

    - name: checkout repo
      uses: actions/checkout@master

    - name: get version from GITHUB_REF
      id: get_version
      run: |
        GITREV="${GITHUB_REF/refs\/tags\//}"
        echo "VERSION=${GITREV:4}" >> "$GITHUB_OUTPUT"

    - name: write version to pubspec.yaml
      run: |
        sed -i.bak -E "s/version: [0-9]+\.[0-9]+\.[0-9]+(\+[0-9]+)?/version: ${{steps.get_version.outputs.VERSION }}/g" pubspec.yaml && rm pubspec.yaml.bak

    - name: apt update
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y

    - name: Install build dependencies
      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

    - name: Set Up Java
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'
        channel: 'master'

    - name: Install flutter dependencies
      run: flutter pub get

    - name: Build linux
      run: flutter build linux --release

    - name: zip data
      run: |
        zip -r "./mfl-terminal-linux-${{ inputs.arch }}.zip" ./build/linux/${{ inputs.arch }}/release/bundle/*

    - name: Upload zip to release
      uses: softprops/action-gh-release@v2
      with: 
        files: "./terminal/mfl-terminal-linux-${{ inputs.arch }}.zip"